import { Injectable } from '@nestjs/common';
import { DatabaseService } from 'src/database.service';

@Injectable()
export class QueryService {
  constructor(private readonly databaseService: DatabaseService) {}

  cleanSQLQueryResponse(query: string) {
    return query.replace(/```sql|```/g, '').trim();
  }

  async getTableStructure(
    tables: Record<string, string[]>,
  ): Promise<Record<string, any[]>> {
    return {
      empresas: [
        {
          column: 'id_empresas',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: true,
        },
        {
          column: 'nombre',
          type: 'varchar(200)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'razon_social_cliente',
          type: 'varchar(200)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'cuit_cliente',
          type: 'char(200)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'activa',
          type: 'tinyint(1)',
          default: '1',
          comment: '0:no; 1:si; si esta usando el sistema',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'nacionalidad',
          type: "enum('argentina','chilena','bolivia','brasil','colombia','ecuador','paraguay','peru','uruguay','venezuela','canada','suecia','singapur','mexico')",
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'id_grupos',
          type: 'char(36)',
          default: 'N/A',
          comment: 'si pertenece a algun grupo',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'periodo_inicio_proceso',
          type: 'date',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'codigo',
          type: 'varchar(150)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'fecha_hora_carga',
          type: 'timestamp',
          default: 'CURRENT_TIMESTAMP',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'eliminado',
          type: 'tinyint(1)',
          default: '0',
          comment: '0:no;1:si',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'zendesk_chat',
          type: 'tinyint(1)',
          default: '0',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
      ],
      proveedores: [
        {
          column: 'id_proveedores',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: true,
        },
        {
          column: 'cuit',
          type: 'char(20)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'id_empresas',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: true,
          referenced_table: 'empresas',
          referenced_column: 'id_empresas',
          isPrimaryKey: false,
        },
        {
          column: 'activo_empresa',
          type: 'tinyint(1)',
          default: '1',
          comment: '0:no; 1:si; si esta activo para la empresa',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'nombre_razon_social',
          type: 'varchar(255)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'nombre_comercial',
          type: 'varchar(255)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'domicilio_legal',
          type: 'varchar(255)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'email',
          type: 'varchar(255)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
      ],
      empleados: [
        {
          column: 'id_empleados',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: true,
        },
        {
          column: 'id_proveedores',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: true,
          referenced_table: 'proveedores',
          referenced_column: 'id_proveedores',
          isPrimaryKey: false,
        },
        {
          column: 'apellido',
          type: 'varchar(50)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'nombre',
          type: 'varchar(50)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'dni',
          type: 'char(20)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'cuil',
          type: 'char(20)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'estado',
          type: 'bigint(1)',
          default: '1',
          comment: 'ver tabla estados',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'anulado',
          type: 'bigint(1)',
          default: 'N/A',
          comment: '0:no;1:si',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'eliminado',
          type: 'tinyint(1)',
          default: '0',
          comment: '0:no; 1:si; indica si fue eliminado',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'baja_afip',
          type: 'tinyint(1)',
          default: '0',
          comment: '0:no;1:si; indica si se dio de baja definitiva',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'id_motivos_baja_afip',
          type: 'int(1)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'fecha_baja_afip',
          type: 'date',
          default: 'N/A',
          comment: 'para calcular las 48hs ',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'estado_doc_baja',
          type: 'bigint(1)',
          default: '1',
          comment:
            'campo que indica el estado de los documentos que tiene que presentar cuando está de baja',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'sexo',
          type: 'bigint(1)',
          default: 'N/A',
          comment: '1:M;2:F',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'fecha_nacimiento',
          type: 'date',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
      ],
      documentos: [
        {
          column: 'id',
          type: 'int(1)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: true,
        },
        {
          column: 'id_documentos',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'id_usuarios_carga',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: true,
          referenced_table: 'usu_usuarios',
          referenced_column: 'id_usuarios',
          isPrimaryKey: false,
        },
        {
          column: 'fecha_hora_creacion',
          type: 'timestamp',
          default: 'CURRENT_TIMESTAMP',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'id_documentos_tipos',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: true,
          referenced_table: 'documentos_tipos',
          referenced_column: 'id_documentos_tipos',
          isPrimaryKey: false,
        },
        {
          column: 'id_documentos_reglas',
          type: 'int(1)',
          default: 'N/A',
          comment:
            'id de la regla bajo la cual actualmente se pide un documento',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: true,
          referenced_table: 'documentos_reglas',
          referenced_column: 'id_documentos_reglas',
          isPrimaryKey: false,
        },
        {
          column: 'tipo_entidad',
          type: "enum('empleado','vehiculo','proveedor','socio','planes_pago','ordenes_compra')",
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'modulo',
          type: "enum('datos_especificos','datos_generales','datos_impositivos','datos_laborales','socios','trabajadores','transporte_internacional','vehiculos','planes_pago','datos_hys','ordenes_compra')",
          default: 'N/A',
          comment: 'usado para proveedores mas que nada',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'id_entidad',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'estado',
          type: 'bigint(1)',
          default: '1',
          comment: 'ver tabla estados',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'fecha_vencimiento',
          type: 'date',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'estado_doc',
          type: 'bigint(1)',
          default: '1',
          comment: 'guarda el estado del documento no aprobado',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'fecha_vencimiento_doc',
          type: 'date',
          default: 'N/A',
          comment: 'guarda la fecha de vto del doc no aprobado',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'nombre_archivo',
          type: 'varchar(100)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'fecha_inicio',
          type: 'date',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'mes',
          type: 'int(1)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'anio',
          type: 'int(1)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'categoria',
          type: 'varchar(100)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'campo_extra1',
          type: 'varchar(250)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'campo_extra2',
          type: 'varchar(250)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'campo_extra3',
          type: 'varchar(250)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'campo_extra4',
          type: 'varchar(250)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'campo_extra5',
          type: 'varchar(250)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'estado_baja',
          type: 'tinyint(1)',
          default: '0',
          comment: '0:no;1:si indica si se dio la baja',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'tipo_baja',
          type: "enum('automatica','usuario_proveedor','usuario_sistema')",
          default: 'N/A',
          comment: 'quien da la baja',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'motivo_baja',
          type: 'varchar(255)',
          default: 'N/A',
          comment: 'solo si no es automatica',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'id_usuarios_revisa1',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: true,
          referenced_table: 'usu_usuarios',
          referenced_column: 'id_usuarios',
          isPrimaryKey: false,
        },
        {
          column: 'fecha_revision1',
          type: 'datetime',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'resultado_revision1',
          type: 'bigint(1)',
          default: '1',
          comment: '1,2,3:rechazado; 4:aprobado',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'id_usuarios_revisa2',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: true,
          referenced_table: 'usu_usuarios',
          referenced_column: 'id_usuarios',
          isPrimaryKey: false,
        },
        {
          column: 'fecha_revision2',
          type: 'datetime',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'resultado_revision2',
          type: 'bigint(1)',
          default: '1',
          comment: '1,2,3:rechazado; 4:aprobado',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'observacion_revision',
          type: 'varchar(500)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'observacion_interna',
          type: 'varchar(500)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'fecha_hora_modifica',
          type: 'datetime',
          default: 'N/A',
          comment: 'se actualiza por trigger',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'tarea_proveedor',
          type: 'varchar(255)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'riesgos_proveedor',
          type: 'varchar(255)',
          default: 'N/A',
          comment: 'todos los ids de los riesgos del proveedor',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'rs_asistencia',
          type: 'tinyint(1)',
          default: 'N/A',
          comment: 'para recibo de sueldo profundo',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'rs_dias_falto',
          type: 'bigint(20)',
          default: 'N/A',
          comment: 'para recibo de sueldo profundo',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'rs_horas_trabajadas',
          type: 'int(1)',
          default: 'N/A',
          comment: 'para recibo de sueldo profundo',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'rs_sueldo_neto',
          type: 'double',
          default: 'N/A',
          comment: 'para recibo de sueldo profundo',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'rs_incluye_vacaciones',
          type: 'tinyint(1)',
          default: 'N/A',
          comment: 'para recibo de sueldo profundo',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'rs_control_descarga_dias',
          type: 'int(1)',
          default: 'N/A',
          comment: 'para recibo de sueldo profundo',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'rs_km_recorridos',
          type: 'int(1)',
          default: 'N/A',
          comment: 'para recibo de sueldo profundo',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'rs_km_50_recorridos',
          type: 'int(1)',
          default: 'N/A',
          comment: 'para recibo de sueldo profundo al 50%',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'rs_km_100_recorridos',
          type: 'int(1)',
          default: 'N/A',
          comment: 'para recibo de sueldo profundo al 100%',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'rs_horas_nocturnas',
          type: 'int(1)',
          default: 'N/A',
          comment: 'para recibo profundo, usado en convenio seguridad',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'rs_50_horas',
          type: 'int(1)',
          default: 'N/A',
          comment: 'para recibo profundo, usado en uocra al 50%',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'rs_100_horas',
          type: 'int(1)',
          default: 'N/A',
          comment: 'para recibo profundo, usado en uocra al 100%',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'id_aptos_medicos_tipos',
          type: 'int(11)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: true,
          referenced_table: 'aptos_medicos_tipos',
          referenced_column: 'id_aptos_medicos_tipos',
          isPrimaryKey: false,
        },
        {
          column: 'id_obras',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'obs_controlador',
          type: 'text',
          default: 'N/A',
          comment:
            'si un doc pendiente no se debe controlar, en este campo se guarda la observación',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'obs_controlador_fecha_hora',
          type: 'datetime',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'obs_controlador_id_usuarios',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'obs_contratista',
          type: 'text',
          default: 'N/A',
          comment:
            'campo para guardar las aclaraciones que quiera hacer la persona que carga un documento',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'rechazo_detalle_menor',
          type: 'int(1)',
          default: 'N/A',
          comment:
            '1: el doc ha sido rechazado por un detalle menor, 0: rechazo por detalle no menor',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'se_pide',
          type: 'int(1)',
          default: '0',
          comment:
            'indica si el documento actualmente se le pide. 1:si; 0: no ',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'se_pide_obligatorio',
          type: 'int(1)',
          default: '0',
          comment:
            'indica si el documento actualmente se le pide y es obligatorio. 1:si; 0: no',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'id_empresas',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'control_automatico_estado',
          type: 'int(1)',
          default: '0',
          comment:
            '0:no;1:procesando;2:rechazado;4:pre-aprobado;5:aprobado por api;6:rechazado por api',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'fecha_cambio_estado',
          type: 'date',
          default: 'N/A',
          comment: 'guardo la fecha de cuando cambia el estado de el documento',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'estado_proceso_aprob',
          type: 'tinyint(1) unsigned',
          default: 'N/A',
          comment:
            '0:no;1:procesando;2:rechazado;4:pre-aprobado;5:aprobado por api;6:rechazado por api',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'notificacion_enviada',
          type: 'int(1)',
          default: '0',
          comment:
            'Para Hemco Nicaragua - campo guarda estado de envio de notificacion para record de policia',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'fecha_rechazo',
          type: 'datetime',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'id_transaccion',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'can_controller_audit',
          type: 'tinyint(1)',
          default: '1',
          comment: '',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'status_api_iacontroller',
          type: 'tinyint(4)',
          default: 'N/A',
          comment: '1: Pendiente, 2: Levantado, 3: Rechazado, 4: Aprobado',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'status_api',
          type: 'tinyint(4)',
          default: 'N/A',
          comment: '1: Pendiente, 2: Levantado, 3: Rechazado, 4: Aprobado',
          notNull: false,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
      ],
      documentos_tipos: [
        {
          column: 'id_documentos_tipos',
          type: 'char(36)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: true,
        },
        {
          column: 'nombre',
          type: 'varchar(200)',
          default: 'N/A',
          comment: '',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'tipo',
          type: "enum('general','laboral')",
          default: 'N/A',
          comment: 'indica que tipo de documento es',
          notNull: false,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'tipos_entidad_mostrar',
          type: 'varchar(100)',
          default: 'N/A',
          comment: 'empleado,vehiculo,proveedor,socio,planes_pago',
          notNull: true,
          autoIncrement: false,
          characterSet: 'utf8',
          collation: 'utf8_general_ci',
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'fecha_vencimiento',
          type: 'tinyint(1)',
          default: 'N/A',
          comment: '0:no;1:si',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'nombre_archivo',
          type: 'tinyint(1)',
          default: 'N/A',
          comment: '0:no;1:si',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'fecha_inicio',
          type: 'tinyint(1)',
          default: 'N/A',
          comment: '0:no;1:si',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'mes',
          type: 'tinyint(1)',
          default: 'N/A',
          comment: '0:no;1:si',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
        {
          column: 'anio',
          type: 'tinyint(1)',
          default: 'N/A',
          comment: '0:no;1:si',
          notNull: true,
          autoIncrement: false,
          characterSet: null,
          collation: null,
          isForeignKey: false,
          referenced_table: null,
          referenced_column: null,
          isPrimaryKey: false,
        },
      ],
    };

    const tableStructures: Record<string, any[]> = {};

    for (const [table, columnsToShow] of Object.entries(tables)) {
      const columnQuery = `
        SELECT 
          COLUMN_NAME,
          COLUMN_TYPE,
          IS_NULLABLE,
          COLUMN_DEFAULT,
          COLUMN_COMMENT,
          CHARACTER_SET_NAME,
          COLLATION_NAME,
          COLUMN_KEY  -- Agregar COLUMN_KEY aquí
        FROM 
          INFORMATION_SCHEMA.COLUMNS 
        WHERE 
          TABLE_NAME = '${table}' 
          AND TABLE_SCHEMA = 'bd_infocontrol_desarrollo';`;

      const foreignKeyQuery = `
        SELECT 
          kcu.COLUMN_NAME,
          kcu.REFERENCED_TABLE_NAME,
          kcu.REFERENCED_COLUMN_NAME
        FROM 
          INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
        JOIN 
          INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc ON kcu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
        WHERE 
          tc.CONSTRAINT_TYPE = 'FOREIGN KEY'
          AND kcu.TABLE_NAME = '${table}' 
          AND kcu.TABLE_SCHEMA = 'bd_infocontrol_desarrollo';`;

      const [columnsInfo, foreignKeys] = await Promise.all([
        this.databaseService.executeQuery(columnQuery),
        this.databaseService.executeQuery(foreignKeyQuery),
      ]);

      tableStructures[table] = this.parseAndSanitizeColumnInfo(
        columnsInfo,
        foreignKeys,
        columnsToShow,
      );
    }

    return tableStructures;
  }

  private parseAndSanitizeColumnInfo(
    columnsInfo: any[],
    foreignKeys: any[],
    columnsToShow: string[],
  ): any[] {
    const foreignKeyMap = new Map(
      foreignKeys.map(
        ({ COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME }) => {
          return [
            COLUMN_NAME,
            {
              referenced_table: REFERENCED_TABLE_NAME,
              referenced_column: REFERENCED_COLUMN_NAME,
            },
          ];
        },
      ),
    );

    return columnsInfo
      .filter(({ COLUMN_NAME }) => columnsToShow.includes(COLUMN_NAME))
      .map(
        ({
          COLUMN_NAME,
          COLUMN_TYPE,
          COLUMN_DEFAULT,
          COLUMN_COMMENT,
          IS_NULLABLE,
          CHARACTER_SET_NAME,
          COLLATION_NAME,
          COLUMN_KEY,
        }) => ({
          column: COLUMN_NAME,
          type: COLUMN_TYPE,
          default: COLUMN_DEFAULT || 'N/A',
          comment: COLUMN_COMMENT || '',
          notNull: IS_NULLABLE === 'NO',
          autoIncrement: COLUMN_TYPE.includes('auto_increment'),
          characterSet: CHARACTER_SET_NAME || null,
          collation: COLLATION_NAME || null,
          isForeignKey: foreignKeyMap.has(COLUMN_NAME),
          referenced_table:
            foreignKeyMap.get(COLUMN_NAME)?.referenced_table || null,
          referenced_column:
            foreignKeyMap.get(COLUMN_NAME)?.referenced_column || null,
          isPrimaryKey: COLUMN_KEY === 'PRI',
        }),
      );
  }

  public async extractAndSanitizeQuery(data: any): Promise<string> {
    const content = data?.choices?.[0]?.message?.content;
    if (!content) {
      throw new Error('Content not found in the input data');
    }

    const sanitizedQuery = this.sanitizeQuery(content);
    return sanitizedQuery;
  }

  private sanitizeQuery(query: string): string {
    query = query.replace(/```sql\n?/g, '').replace(/```/g, '');

    query = query.replace(/--.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');

    const allowedCharsRegex = /[^a-zA-Z0-9\s.,*()_=%'`"-]/g;

    const cleanedQuery = query.replace(allowedCharsRegex, '').trim();

    return cleanedQuery;
  }

  extractSqlQuery(text: string): string | null {
    const pattern = /```sql([\s\S]*?)```/;
    const match = text.match(pattern);

    return match ? match[1].trim() : null;
  }
}
